parres-hq/whitenoise_flutter

lib/config/providers/contacts_provider.dart
Add fetch_contacts, add_contact,  remove_contact, update_contacts support
=> Add contacts provider

lib/src/rust/api.dart, lib/src/rust/frb_generated.dart, rust/src/api/mod.rs, rust/src/frb_generated.rs
* Update all bridge methods to take Pubkey, not Account.
* Remove unused helper method
* Regenerate
* Rust format
=> Bridge uses pubkeys not accounts (#76)

lib/config/providers/group_provider.dart, lib/domain/models/contact_model.dart, lib/ui/contact_list/group_chat_details_sheet.dart, lib/ui/contact_list/new_group_chat_sheet.dart, test/config/providers/group_provider_test.dart
**Problem:**
The contact list was being reprocessed on every build cycle, including when users typed in the search field, causing performance issues and unnecessary async operations. Additionally, the group creation flow needed to be connected to the backend API via the group provider.
**Solution:**
- **Cached contact conversion**: Store processed ContactModels to avoid repeated PublicKey-to-npub conversions
- **Smart processing trigger**: Only process contacts when the underlying data actually changes
- **Synchronous filtering**: Made search filtering instant by operating on cached data
- **Removed FutureBuilder**: Eliminated rebuild triggers in the widget tree
- **Real PublicKey usage**: Replaced temporary hashCode IDs with actual npub strings from `exportAccountNpub()`
- **Proper API …
=> creat group impl

lib/ui/settings/general_settings_screen.dart, rust/Cargo.lock, rust/Cargo.toml
This wires up the delete all data button with the API method and creates a dialog.
=> Delete all data working

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/config/providers/auth_provider.dart, lib/config/providers/contacts_provider.dart, lib/src/rust/api.dart, lib/src/rust/frb_generated.dart, lib/src/rust/frb_generated.io.dart, lib/ui/auth_flow/login_screen.dart, lib/ui/settings/nostr_keys/nostr_keys_screen.dart, pubspec.yaml, rust/src/api/mod.rs, rust/src/frb_generated.rs
- Fixes a crash when we entered an incorrect nsec on log in
- Fixes a crash when leaving the keys page
- Fixes a crash when trying to fetch a contact
- Changed version for early alpha
=> Collection of small bug fixes

lib/ui/auth_flow/welcome_screen.dart
=> Remove Alpha Version from login

ios/Podfile.lock, lib/config/providers/contacts_provider.dart, lib/config/providers/group_provider.dart, lib/domain/models/contact_model.dart, lib/ui/contact_list/new_chat_bottom_sheet.dart, lib/ui/contact_list/new_group_chat_sheet.dart, lib/ui/contact_list/start_chat_bottom_sheet.dart, lib/ui/core/ui/custom_app_bar.dart
Fix bug failing to load contacts,  add group creation to start chat card
=> Fix contact list bug

lib/ui/chat/widgets/chat_contact_avatar.dart, lib/ui/contact_list/chat_list_screen.dart
=> Use real avatar on ChatListScreen

lib/ui/settings/general_settings_screen.dart
=> #113 - Edit profile updates now reflects in profile page and account switcher

lib/routing/router_provider.dart, lib/routing/routes.dart, lib/ui/auth_flow/login_screen.dart, lib/ui/core/ui/custom_bottom_sheet.dart, lib/ui/settings/profile/connect_profile_bottom_sheet.dart, lib/ui/settings/profile/switch_profile_bottom_sheet.dart
Added profiles feature for:
- logging in existing account
- creating new account
Polished account switcher:
- highlight the current active account
- always put the active account at the top of the accounts (profiles) list
Bug fixes, enhancements.
=> Add and Switch Profile

ios/Podfile.lock, lib/ui/core/ui/app_text_form_field.dart
=> patch: disable AppTextFormField interactive selection on read-only mode.

ios/Podfile.lock, lib/routing/router_provider.dart, lib/routing/routes.dart, lib/ui/chat/widgets/chat_input.dart, lib/ui/settings/general_settings_screen.dart, lib/ui/settings/profile/edit_profile_screen.dart, lib/ui/settings/profile/share_profile_screen.dart, pubspec.lock, pubspec.yaml
Added share profile feature with QR code functionality
- Created new ShareProfileScreen with user profile
display, QR code generation, and copy-to-clipboard
functionality
- Added routing support for the share profile screen
- Integrated share profile button in general settings
- Added QR code dependency (qr_flutter) for generating
profile QR codes
- Minor UI adjustments including button size
optimization
=> Share profile

lib/config/providers/nostr_keys_provider.dart, lib/config/states/nostr_keys_state.dart, lib/config/states/nostr_keys_state.freezed.dart, lib/ui/core/ui/app_text_form_field.dart, lib/ui/settings/nostr_keys/nostr_keys_screen.dart
Updated Profile Keys UI
Improved Notifier impls
=> Refactor Nostr keys management and UI

lib/src/rust/api/relays.dart, lib/src/rust/frb_generated.dart, lib/src/rust/frb_generated.io.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/api/relays.rs, rust/src/frb_generated.rs
=> Relay status

ios/Podfile.lock, lib/ui/contact_list/chat_list_screen.dart, lib/ui/contact_list/start_chat_bottom_sheet.dart, lib/ui/contact_list/widgets/profile_ready_card.dart
Fixes #200 
Fixes #179 
Fixes text on blank chats page
=> Collection of small fixes

lib/config/providers/auth_provider.dart, lib/ui/contact_list/new_chat_bottom_sheet.dart, lib/ui/core/ui/custom_textfield.dart, lib/ui/settings/app_settings/app_settings_screen.dart, lib/ui/settings/general_settings_screen.dart
=> Fix #199, #205 and contact search

lib/ui/contact_list/new_chat_bottom_sheet.dart
=> Null safe contacts search

lib/ui/auth_flow/info_screen.dart
=> Fix #150 (Make InfoScreen scrollable)

ios/Podfile.lock, lib/config/providers/chat_provider.dart, lib/ui/contact_list/legacy_invite_bottom_sheet.dart
Implement Legacy NIP-04 Direct Messages
This PR implements the sendDirectMessageNip04 functionality to support
legacy direct messaging through NIP-04 encryption for contacts who haven't
migrated to MLS yet.
Changes Made:
- Complete NIP-04 Implementation: Finished the sendLegacyNip04Message method
in ChatProvider with proper message content parameter, error handling, and
logging
- Fixed Invite System: Updated the legacy invite bottom sheet to pass the
required message parameter and handle the boolean return value correctly
- Enhanced Error Handling: Added comprehensive error handling with proper
WhitenoiseError conversion and logging for debugging
Key Features:
- Uses standard NIP-04 encryption for secure legacy direct messages
- Validates user authentication before sending messages
- …
=> impl legacy DM

ios/Runner.xcodeproj/project.pbxproj, lib/config/providers/chat_provider.dart
=> Implement replies, reactions and message deleting to ChatProvider

lib/config/providers/chat_provider.dart, lib/utils/message_converter.dart
- Enhanced group chat with user metadata loading
Updated MessageConverter to fetch and display real user metadata (names, nip05, profile
pictures) from the Nostr network instead of generic placeholders. Messages now show proper
user information with fallback to contacts provider when metadata is unavailable.
=> fix members display in chat

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/config/providers/account_provider.dart, lib/src/rust/api/utils.dart, lib/src/rust/frb_generated.dart, lib/ui/auth_flow/create_profile_screen.dart, pubspec.lock, pubspec.yaml, rust/src/api/utils.rs, rust/src/frb_generated.rs
=> 178 add upload avatar

lib/ui/chat/chat_screen.dart, lib/ui/chat/widgets/chat_bubble/bubble.dart, lib/ui/chat/widgets/message_widget.dart
Fixed chat bubble tail
Fixed padding issues in chat bubble
Fixed margin issues in chat bubble
=> patch: chat ui fixes

android/app/src/main/AndroidManifest.xml
=> Update app name on Android to "White Noise"

lib/ui/chat/services/chat_dialog_service.dart
+ add copying msgs functionality
=> Add message deleting to UI

ios/Podfile.lock, lib/config/providers/auth_provider.dart, lib/ui/settings/profile/connect_profile_bottom_sheet.dart
Improves account management by saving existing accounts before login and ensuring they are not lost when a new account is added. Updates the login flow to set the authenticated state before setting the active account, adds logging for account state changes, and modifies the connect profile bottom sheet to avoid logging out the current account when navigating to the login screen.
=> Fix existing account login

lib/ui/chat/widgets/reaction/reaction_default_data.dart, lib/ui/chat/widgets/reaction/reactions_dialog_widget.dart
Improve chat message 
interactions and reactions UI
Changes Made
Security Enhancement:
- Remove delete option for 
other users' messages - Users
can now only delete their own
messages, preventing accidental
deletion of others' content
UI/UX Improvements:
- Fix reaction list squishing 
on small screens - Implemented
responsive layout that wraps
reactions to multiple rows when
screen width is limited
Files Modified
1. lib/ui/chat/widgets/reaction
/reaction_default_data.dart
- Removed delete option from
default menu items for non-user
messages
- Users' own messages still
show: Edit, Copy, Delete
- Others' messages now show:
Reply, Copy (no delete)
2. lib/ui/chat/widgets/reaction
/reactions_dialog_widget.dart
- Added responsive layout
system with screen size
detection
- Large screens …
=> hide delete for not my messages

ios/Podfile.lock, lib/ui/auth_flow/create_profile_screen.dart, lib/ui/auth_flow/info_screen.dart
- Remove "Free Citizen" default text from profile creation screen
- Add petname loading logic to info screen before navigation  
- Show loading state until displayName is available
- Prevent navigation to profile screen until account data is loaded
=> Fix petname loading

ios/Podfile.lock, lib/routing/chat_navigation_extension.dart, lib/ui/contact_list/contact_loading_bottom_sheet.dart, lib/ui/contact_list/group_chat_details_sheet.dart, lib/ui/contact_list/new_chat_bottom_sheet.dart, lib/ui/contact_list/safe_toast_mixin.dart, lib/ui/contact_list/search_chat_bottom_sheet.dart, lib/ui/contact_list/share_invite_bottom_sheet.dart, lib/ui/contact_list/start_chat_bottom_sheet.dart, lib/ui/core/ui/custom_bottom_sheet.dart, lib/ui/core/ui/custom_textfield.dart, lib/ui/settings/network/add_relay_bottom_sheet.dart, lib/ui/settings/profile/connect_profile_bottom_sheet.dart, lib/ui/settings/profile/share_profile_qr_scan_screen.dart, lib/ui/settings/profile/switch_profile_bottom_sheet.dart
Enhanced Custom Bottom Sheet 
Component
Flexible & Keyboard-Aware 
Design
- Dynamic height calculation -
Bottom sheet now automatically
adjusts to content size with
proper constraints
- Improved keyboard handling -
Better viewport management when
keyboard appears, preventing
content overflow
- Enhanced SafeArea 
implementation - Repositioned
SafeArea wrapper for proper
padding on devices with notches
and home indicators (also adjusted for status bar height of 54)
Visual & UX Improvements
- Consistent theming - Replaced
hardcoded colors with
theme-aware
context.colors.overlay for
proper light/dark mode support
- Smoother animations -
Enhanced transition timing and
visual feedback
Developer Experience
- Cleaner API - Simplified
bottom sheet configuration with
sensible defaults
- Better …
=> Bottom sheet fix

rust/Cargo.lock, rust/Cargo.toml
=> Bump rust crate

DEBUGGIN.md
=> Finding rust logs in ios emulator

README.md
In this PR #374 we realized that there are missing instructions in the README on how to test the app locally with a local relays and blossom server.
This PR adds a very short comment on how to set them up
=> docs: add brief comment about running local relay and blossom server

lib/ui/contact_list/new_chat_bottom_sheet.dart, lib/ui/core/ui/wn_bottom_sheet.dart
Added a `useSafeArea` parameter to WnBottomSheet for more flexible safe area usage. Updated NewChatBottomSheet to disable safe area, and refactored its layout to improve scroll behavior and content padding.
=> Fix #392 - Scrollable NewChatBottomSheet

lib/routing/router_provider.dart, lib/routing/routes.dart, lib/ui/contact_list/new_chat_bottom_sheet.dart, lib/ui/settings/profile/share_profile_qr_scan_screen.dart
Introduces a new route and UI for scanning contact QR codes from the new chat bottom sheet. Updates routing, adds a scan button to the contact search field, and modifies the QR scan screen to optionally hide the 'View QR Code' button for this flow.
=> Add (#352) contact QR scan feature to new chat sheet

ios/Podfile.lock, lib/ui/chat/chat_screen.dart, lib/ui/chat/widgets/chat_search_widget.dart, lib/ui/chat/widgets/message_widget.dart
The chat search functionality has been updated. The UI colors for the search results counter and navigation arrows were adjusted to match the theme. Search result highlighting has been improved: non-matching messages and non-matching text within matching messages are now colored with mutedForeground to make search results clearer.
=> Fix search in chat colors and highlighting

lib/ui/core/ui/wn_text_field.dart
=> Use Filled variant in Add Relay when user types

assets/svgs/ic_arrows_vertical.svg, ios/Podfile.lock, lib/ui/contact_list/widgets/contact_list_tile.dart, lib/ui/core/themes/assets.dart, lib/ui/settings/general_settings_screen.dart
=> Swap Share Profile and Switch Account

lib/ui/contact_list/widgets/contact_list_tile.dart, lib/ui/settings/general_settings_screen.dart
https://github.com/user-attachments/assets/bbaaa9a1-9d07-4bcc-9239-6281469eb7ac
Fixes #434
=> Don't show a loading state for npub in general settings screen

lib/src/rust/api/accounts.dart, lib/src/rust/frb_generated.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/api/accounts.rs, rust/src/frb_generated.rs
=> Introduce load_account bridge function
